HOST_IP = "localhost"
USER = "root"
PASSWORD = "fireball"
GROUP_NAME = "GroupA"
DEVICE_ID = "DeviceA"

MQTT_HOSTNAME = "nam1.cloud.thethings.network"
MQTT_USERNAME = "adam-test-appdsfsdfds@ttn"
MQTT_API_KEY = "NNSXS.QPHB536RLPYNBZVDEPGZZJQEF7AU33CUMHTMRBY.IGYVR5SDX4H6JFCV5PXQ7U6ILOSIOX5Q2E5HODQGATBE5RWH4JWA"
MQTT_PORT = 1883
MQTT_TOPIC = "#"

